version: '3.1'

services:

  mongo:
    image: mongo:4.0.28
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"

  api:
    build: .
    ports:
      - "8085:8080"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"


volumes:
  db: